# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BeWaq0b05rHbdH0UguiUYiKxhdV645bH
"""

from scipy.stats import bernoulli
#number of samples is 100000 1 denotes head and 0 denotes tail
simlen=100000
#probability of event coin is head i.e,X=1 for head
p1=1/2
#probability of event that A speaks truth i.e,X=1 for truth
p2=4/5
#Generating sample date for coin using Bernoulli r.v.
data_coin = bernoulli.rvs(size=simlen,p=p1)
#Generating sample date for truth using Bernoulli r.v.
data_truth= bernoulli.rvs(size=simlen,p=p2)
#take a variable which counts the outcomes where A reports its as Head and it was actually a Head as act_head
act_head=0
for i in range(simlen):
  for j in range(simlen):
    if data_coin[i]==1 and data_truth[j]==1:
      act_head+=1
#take a variable which counts the outcomes where A reports it as Head but it was not actually a head as notact_head
notact_head=0
for i in range(simlen):
  for j in range(simlen):
    if data_coin[i]==0 and data_truth[j]==0:
      notact_head+=1
#calculating probability that it was actually a head given A reports it as Head
sim_prob=act_head/(act_head+notact_head)
#actual probability
theo_prob=(p2*p1)/((p1*p2)+((1-p1)*(1-p2)))
#theory vs simulation
print("The probability calculated using simulation is :",sim_prob)
print("The probability calculated theritically is :",theo_prob)