# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LY3_LrC8e8d0cZFD1A5YoYXHYi_RBQXR
"""

# import required libraries
from scipy.stats import norm
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
 
# Creating the distribution
data = np.arange(-20,100,0.01)
pdf = norm.pdf(data , loc = 40, scale = 5.1 )
#loc=mean=40 ,scale=standard deviation=5.1

#Probability of project completed within 40 days.
prob= norm(loc = 40, scale = 5.1).cdf(40)
print("The probability that project will be completed within 40 days is",prob)
 
#Visualizing the distribution
 
sb.set_style('whitegrid')
sb.lineplot(data, pdf , color = 'red')
plt.xlabel('x')
plt.ylabel('f(x)')