# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpFIyUALJ24U407U_RPmKZ-LpVTdDuGG
"""

import matplotlib.pyplot as plt
#PDF of X
x = [-2,4,10]
y = [1/12,1/12,1/12] 
plt.plot(x, y)
plt.xlabel('x')
plt.show()
#PDF of Y
x = [-10,2,14]
y = [1/24,1/24,1/24] 
plt.plot(x, y)
plt.xlabel('y')
plt.show()
#CDF of X
x = [-4,-2,4,10,11]
y = [0,0,1/2,1,1] 
plt.plot(x, y)
plt.xlabel('x')
plt.show()
#CDF of Y
x = [-16,-10,2,14,16]
y = [0,0,1/2,1,1] 
plt.plot(x, y)
plt.xlabel('y')
plt.show()